coverage:
  status:
    project:
      default:
        threshold: 3%
    patch:
      default:
        threshold: 5%

comment:
  require_changes: true

ignore:
- ".gitignore"
- "**/*.yml"
- "cover*"
- "testdata*"
